name: API UPDATER

on:
  push:
    paths:
      - 'API/SMS/SMS.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py
    - name: Install dependencies  
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: AUTOMATED API UPDATE
        file_pattern: API/SMS/SMS.json
        push_options: '--force'
