name: API UPDATER

on:
  push:
    paths:
      - 'API/SMS/SMS.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py
    - name: Install dependencies  
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        branch: feature-123
        commit_options: '--no-verify --signoff'
        file_pattern: API/SMS/SMS.json
        repository: .
        tagging_message: 'v1.0.0'
        status_options: '--untracked-files=no'
        add_options: '-u'
        push_options: '--force'
        skip_dirty_check: true
        skip_fetch: true
        skip_checkout: true
        disable_globbing: true
        create_branch: true
